name:                tp
version:             0.1.0.0
github:              "bartavelle/tp"
license:             BSD3
author:              "Simon Marechal"
maintainer:          "simon@banquise.net"
copyright:           "Simon Marechal"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bartavelle/tp#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- hspec
- QuickCheck
- random
- mtl
- microlens-platform

library:
  source-dirs: src

ghc-options:
  - -Wall

executables:
  tp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - tp

tests:
  tp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tp